username: <username>
password: <password>
phone_number: <phone_number>

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'


positions:
- Software Engineer


locations:
- Michigan
- Remote

salary: 60,000
rate: 25
# --------- Optional Parameters -------
uploads:
  Resume: ./files/cv.pdf
  Cover Letter: ./files/cl.pdf
  #Photo: # PATH TO photo


output_filename:
- ./files/data/out.csv

# blacklist:
# - # Company names you want to ignore

experience_level:
  # - 1 # Entry level
  # - 2 # Associate
  # - 3 # Mid-Senior level
  # - 4 # Director
  # - 5 # Executive
  # - 6 # Internship